// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAykSc8XgFtF3d4yR_cC4ig2GM0ns-ddp8',
    appId: '1:852142844109:web:537eabd352c1f706cea184',
    messagingSenderId: '852142844109',
    projectId: 'trackly-0643',
    authDomain: 'trackly-0643.firebaseapp.com',
    storageBucket: 'trackly-0643.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExEGX85LZJ9bmNWLHDoBWTGwJheTSgV4',
    appId: '1:852142844109:android:e4ef47070d0e42f1cea184',
    messagingSenderId: '852142844109',
    projectId: 'trackly-0643',
    storageBucket: 'trackly-0643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ844oJWdjJTfIamiZYeRUHJKH5VEG2Dg',
    appId: '1:852142844109:ios:af9bd56f53bc18d6cea184',
    messagingSenderId: '852142844109',
    projectId: 'trackly-0643',
    storageBucket: 'trackly-0643.firebasestorage.app',
    iosBundleId: 'com.example.trackly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ844oJWdjJTfIamiZYeRUHJKH5VEG2Dg',
    appId: '1:852142844109:ios:af9bd56f53bc18d6cea184',
    messagingSenderId: '852142844109',
    projectId: 'trackly-0643',
    storageBucket: 'trackly-0643.firebasestorage.app',
    iosBundleId: 'com.example.trackly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAykSc8XgFtF3d4yR_cC4ig2GM0ns-ddp8',
    appId: '1:852142844109:web:609303202c52a5ffcea184',
    messagingSenderId: '852142844109',
    projectId: 'trackly-0643',
    authDomain: 'trackly-0643.firebaseapp.com',
    storageBucket: 'trackly-0643.firebasestorage.app',
  );
}
